### ISSUE TITLE
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' 

### ISSUE THREAD

**Issue by Ridder90** [clue/docker-adminer#27]
Hi there, 

Not sure if this is the right place but I can't seem to connect to mysql when using this image. This my compose file:

```
https-portal:
  image: steveltn/https-portal
  ports:
    - 80:80
    - 443:443
  links:
    - wordpress
  environment:
    STAGE: local
    DOMAINS: 'dev.drc.nl -> http://wordpress'
wordpress:
  image: wordpress:php7.1
  links:
    - db:mysql
  environment:
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_DATABASE: wordpress
  volumes:
    - ${PWD}/html:/var/www/html
db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: admin
adminer:
      image: clue/adminer
      links:
        - db:mysql
      ports:
        - 8181:80
```

When trying to login i get `Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'`

**Comment by Ridder90** [comment]
For somebody reading this. i fixed this by specificly naming the db  image 

```
db:
  image: mariadb:latest
  container_name: db
  environment:
    MYSQL_ROOT_PASSWORD: admin
adminer:
  image: adminer
  links:
    - db:3306
  ports:
    - 8080:8080
```
Glad it works now :)
